### ISSUE TITLE
cookie support

### ISSUE THREAD

**Issue by jorsn** [tek/polysemy-http#4]
Is there a reason this has no cookie support? It doesn't seem so difficult to add, since all you need seems to be (on first sight) one record field more in `Request` for the cookie jar, a lens for it and a small change to `nativeRequest`.

**Comment by tek** [comment]
good point! please have a look and tell me whether this satisfies your requirements.

**Comment by tek** [comment]
ping @jorsn

**Comment by jorsn** [comment]
Yeah, sorry. I will look at it until the weekend.

**Comment by tek** [comment]
@jorsn friendly reminder! :smile:

**Comment by jorsn** [comment]
I'm sorry I left this lie around. The commit looks fine to me. In contrast to
`Network.HTTP.Client.responseCookieJar :: Network.HTTP.Client.Response body -> CookieJar`,
you would then access the new cookies directly from the headers, wouldn't you?

**Comment by tek** [comment]
that's right! I think I didn't see a benefit of including the cookie jar in the response.

Uploaded 0.3.1.0!

**Comment by jorsn** [comment]
Thanks! It's probably a bit of relatively simple boilerplate to update the cookie jar (get the 'Cookie' and 'Set-Cookie' headers, replace/insert into the cookie list).

**Comment by tek** [comment]
oh, so you would reuse the jar for the next request?

**Comment by tek** [comment]
@jorsn added the jar to the response!

**Comment by jorsn** [comment]
Ah thanks! I was just writing an answer:

The example is e.g. a login session. I'm not completely sure what I wanted to use polysemy-http for because I then lacked the time, but I think it was downloading papers from IEEE/somewhere automatically based on their doi, which is still on my I'd-like-to-do list. There I need cookies for the login session. I receive them and use them in later requests. Basically this applies to all http conversations where you receive auth tokens as cookies.

**Comment by tek** [comment]
sounds reasonable! maybe the cookies could be stored in an interpreter :thinking:
