### ISSUE TITLE
Map of Headers and queries

### ISSUE THREAD

**Issue by willbasky** [tek/polysemy-http#8]
What about swap lists of Headers to Map from `containers`? 
And the same for queries.

**Comment by tek** [comment]
I think preserving the original order can be useful, and it's the same representation that `http-types` uses.
I'm not entirely opposed to the idea, but since calling `Map.fromList` on the field is a pretty easy helper to build, I'd rather not change it.

**Comment by willbasky** [comment]
Agreed!
